import Layout from '../components/layout'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { connect } from 'react-redux'
import Login from '../components/login'
import { useEffect, useState } from 'react'

const Page = dynamic(() => import('../components/page/Page'), { ssr: false})

const Home = (props) => {
  const [token, setToken] = useState({})

  useEffect(() => {
    setToken(localStorage.getItem('creds'))
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </>
  )
}

const mapStateToProps = (state) => ({
  isLoggedIn: state.auth.isLoggedIn,
  currentUser: state.auth.currentUser
})


Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>
}

export default connect(mapStateToProps)(Home);
